### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrranger** [BearTS/Pterodactyl-v1-DiscordBot#3]
(node:12024) UnhandledPromiseRejectionWarning: Error: SQLITE_NOTADB: file is not a database
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`/home/container/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/container/node_modules/discord.js/src/index.js:8:11)`

**Comment by BearTS** [comment]
NAB, issue with sqlite, reinstall sqlite 
Check your system because i am able to deploy and use it without any issues. 

Next time, mention what node version and OS you are on
